version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
  e2e:
    build:
      context: .
      dockerfile: Dockerfile.e2e
    depends_on:
      - frontend
      - backend
    volumes:
      - ./e2e:/app/e2e
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results 